### ISSUE TITLE
Issues after Installation

### ISSUE THREAD

**Issue by gbyrne2024** [Smiley-McSmiles/jellyman#121]
Hi I really hope you can help me.

I installed the script on Ubuntu Server, latest build and updates. When I was prompted for the install location of my jellyfin it wouldn't detect anything and now my jellyfin is gone. I can reach the page and getting the following when trying to start Jellyfin. Is there anyway to undo this or remove Jellyman and restore the original setup?

Aug 25 00:49:28 gserver systemd[1]: Started jellyfin.service - Jellyfin Media Server - Installed by Jellyman.
Aug 25 00:49:28 gserver (lyfin.sh)[15500]: jellyfin.service: Failed to determine user credentials: No such process
Aug 25 00:49:28 gserver systemd[1]: jellyfin.service: Main process exited, code=exited, status=217/USER
Aug 25 00:49:28 gserver systemd[1]: jellyfin.service: Failed with result 'exit-code'.
administrator@gserver:~$ sudo systemctl stop jellyfin
administrator@gserver:~$ sudo systemctl start jellyfin
administrator@gserver:~$ sudo systemctl status jellyfin
× jellyfin.service - Jellyfin Media Server - Installed by Jellyman
     Loaded: loaded (/usr/lib/systemd/system/jellyfin.service; enabled; preset: enabled)
    Drop-In: /etc/systemd/system/jellyfin.service.d
             └─jellyfin.service.conf
     Active: failed (Result: exit-code) since Sun 2024-08-25 01:01:57 IST; 2s ago
   Duration: 1ms
    Process: 21213 ExecStart=/opt/jellyfin/jellyfin.sh (code=exited, status=217/USER)
   Main PID: 21213 (code=exited, status=217/USER)
        CPU: 578us

**Comment by LarUwU** [comment]
i just solved it by changing the line User='jellyfin' to USER='jellyfin' in the file /opt/jellyfin/jellyfin.sh or the file indicated in ExecStart in the jellyfin.service file

**Comment by gbyrne2024** [comment]
Thanks for your help, but it didn't work. I was able to run the "curl https://repo.jellyfin.org/install-debuntu.sh | sudo bash" script from Jellyfin which repaired my Jellyfin and everything is back.. Phew.

Thanks again for your time.

**Comment by Smiley-McSmiles** [comment]
Marking issue as resolved.
