### ISSUE TITLE
A Rocky install

### ISSUE THREAD

**Issue by cstackpole** [Smiley-McSmiles/jellyman#127]
Greetings,
This weekend I had time to work on this project again. I did a minimal install of Rocky 9.4 and wanted to share some of the issues I ran into.

1) The minimal install didn't include tar nor wget - so the script barreled through the install with loads of failures. After I installed them, I had to remove the user and install directory before I got the script to do the install.

In the setup, it might be worth having something like:
command -v tar || (echo Please ensure tar is in your path && exit 1)
command -v wget || (echo Please ensure wget is in your path && exit 1)

Or maybe just put those as required apps in the instructions.

2) packagesNeededRHEL has a list of packages that seem to not be available for 9
RHEL 8 only:
https://pkgs.org/search/?q=libva-vdpau-driver
Fedora only:
https://pkgs.org/search/?q=libva-intel-media-driver
https://pkgs.org/search/?q=libva-nvidia-driver
https://pkgs.org/search/?q=mesa-va-drivers

3) In the setup.sh script there's this line:
`if [[ $ID_LIKE == .*"rhel".* ]] || [[ $ID == "rhel" ]]; then`

What actually happens is this for a result (running bash with -x):

+ [[ rhel centos fedora == \.\*\r\h\e\l\.\* ]]

I believe the better option is this:
`if [[ "$ID_LIKE" =~ "rhel" ]] || [[ $ID == "rhel" ]]; then`

I've got Jellyfin working, but haven't done much with it yet. I'm still deciding if I want the long term stability of Rocky or the newer packages (but more frequent updates) of Fedora server. If I find anything else, I'll let you know.
Thanks!

**Comment by Smiley-McSmiles** [comment]
Wow, really great info here. I'll for sure submit a patch today addressing these issues. I think I'm just going to put the `wget` and `tar` packages in the required list of packages. I just thought any server distro would definitely include those packages. But that's what I get for assuming.

As for the VA drivers; I'll do some research to figure out what those package names are called. I may have to do some rewriting of the script to handle the differences between RHEL 8/9 and Fedora. We'll see how that works out.

As for the `if` statements, I'll likely accept these changes. I would really love to see some Pull Requests from you in the future. Please don't feel discouraged in contributing in the future :)

Thank you again for this bug report. Information like this is really important.

**Comment by Smiley-McSmiles** [comment]
Okay, adjustments have been made for **Jellyman v1.9.5** Thank you again for your bug report!
