### ISSUE TITLE
Question about -ls "Tell Jellyfin to scan your media library."

### ISSUE THREAD

**Issue by userobvixus** [Smiley-McSmiles/jellyman#4]
The -ls command only scan the entire library or is it possible to do something like "jellyman -ls One Piece" to only refresh my media One Piece ?

**Comment by Smiley-McSmiles** [comment]
At the moment it only scans the entire library. Would love to add that feature. there's a really handy website I'll need to find again that shows all the jellyfin API's. Currently I'm trying to optimize the update functions though. There was a major bug with it but I think I have fixed it. (:

**Comment by userobvixus** [comment]
Thanks for your answer :) 
If you success to add this feature it’s awesome and will help me to automate my jellyfin ! 
Your work is very nice and useful !

**Comment by Smiley-McSmiles** [comment]
You're very welcome, and thank you for the very kind words! I'm trying lol. I can't wait until I have a few people helping me with this project. Development would go so much faster!  Hope you keep enjoying it (:. I'm going to leave this as an open issue for a reminder to add this into Jellyman.

**Comment by Smiley-McSmiles** [comment]
You're very welcome, and thank you for the very kind words! I'm trying lol. I can't wait until I have a few people helping me with this project. Development would go so much faster! Hope you keep enjoying it (:. I'm going to leave this as an open issue for a reminder to add this into Jellyman.

**Comment by LSchallot** [comment]
> At the moment it only scans the entire library. Would love to add that feature. there's a really handy website I'll need to find again that shows all the jellyfin API's. Currently I'm trying to optimize the update functions though. There was a major bug with it but I think I have fixed it. (:

Was it https://api.jellyfin.org/?  I am currently working on a Jellyfin CLI program in Rust and that site has proven extremely useful.  I will also warn you that there are a few bugs with the API (some deletes are broken and I just opened an issue regarding user password).

**Comment by Smiley-McSmiles** [comment]
Oh nice, and I've done some digging and it appears that the [Refresh Library](https://api.jellyfin.org/#tag/Library/operation/RefreshLibrary) API has been changed, and it seems that one can no longer submit a scan of a single directory any more. It may be possible still to submit a Library Scan of a single Library, but one would first need to get the ID of the Library. But I have not tested this of course. What CLI program are you working on?

**Comment by Smiley-McSmiles** [comment]
I am closing this issue as I don't think I'll be adding this feature until Jellyfin updates their APi for this. Would love to continue discuss this. Feel free to message me on [Matrix](app.element.io) `@smiley-mcsmiles:matrix.org`
