### ISSUE TITLE
I'm trying to understand how to use your script

### ISSUE THREAD

**Issue by Nostradamus1973** [Smiley-McSmiles/jellyman#45]
Good morning,

I think I've properly installed your script and confirmed that it's running.
I would like to do daily backup where I would save to a certain folder.
You have listed:
EXAMPLE:
- To stop jellyfin, disable on startup, backup, and then start the jellyfin server:
└── "sudo jellyman -S -d -b /home/$USER/ -s"

If I would like to retain Jellyfin to start at boot, then, would I do this?:
"sudo jellyman -S  -b /home/$USER/ -s"
Where that would simply stop Jellyfin, do a backup, and then start Jellfin. Am I correct?
Since y ou are the creator of this script, have you automated the setup with a cron job or as a command on Linux's startup (i.e. like Ubuntu's Autostart feature)?

Thx for a really cool script.

EDIT: I keep getting an error referring to (addy slightly changed for security)/$USER/Backups/jellyfin-backup.tar': No such file or directory. How can it look for jellyfin-backup.tar when it hasn't been created yet? Read and Write permissions have been given to this directory.
Thx again.

**Comment by Smiley-McSmiles** [comment]
Yes you are correct with that above command. And its saying that the /USER/Backups/ directory doesn't exist, it's just checking if it's there, then it creates it temporarily. It's a normal output so nothing to worry about there. I would recommend looking up how to properly do chron jobs on google. That way I don't tell you wrong information :) Hope you're doing well. We haven't talked in a bit :)
