### ISSUE TITLE
Script has totally destroyed my Jellyfin Installation.....HELP!

### ISSUE THREAD

**Issue by Nostradamus1973** [Smiley-McSmiles/jellyman#46]
Hello again,

This Script has totally destroyed my Jellyfin Installation, I tried using this script to backup Jellyfin , instead it's completely broken my installation.
I confirmed that jellyfin was working after jellyman installation. Then after trying to do a backup the jellyfin.service was not working, trying to restart, stop, start all result in failure.

I guess instead of backing up my data it's totally destroyed it, which is the exact opposite of what I wanted.
Please help
Thank you

**Comment by Nostradamus1973** [comment]
Update: 
I've tried uninstalling jellyfin and reinstalling without any luck, this script must be damaging a lot of system files on Kubuntu 22.04 besides just Jellyfin, given this result. 
I think this script has caused so much damage to my system that I will need to wipe it and start over, this is very upsetting.
Ubuntu users may want to stay away from this script until the creator sorts it out.

**Comment by Smiley-McSmiles** [comment]
I have tested this, and it does not disrupt any other files. It only touches files in the /opt/jellyfin directory.
