### ISSUE TITLE
Jellyfin's compiled ffmpeg

### ISSUE THREAD

**Issue by karserasl** [Smiley-McSmiles/jellyman#52]
Hello,

Can i ask if there is a reason not using the jellyfin's compiled ffmpeg instead of the repos default?

Thanks

**Comment by Smiley-McSmiles** [comment]
Because the jellyfin ffmpeg is only for Ubuntu, and Jellyman aims to be compatible on multiple distributions. You can always install the jellyfin ffmpeg manually if you wish, as long as your on Ubuntu.

**Comment by karserasl** [comment]
I see . Thanks
