### ISSUE TITLE
Installation script does not work

### ISSUE THREAD

**Issue by Mr-Developer-X** [Smiley-McSmiles/jellyman#53]
When installing the script using the setup.sh file. The scripts asks for jellyfin installtion directory. It is looking for metadata folder in  ```{path}//data/metadata``` but jellyfin stores metadata in ```/var/lib/jellyfin/metadata``` and the script doesn move forward from there

**Comment by rbei17** [comment]
same error here. 
Is there any way to fix this ?

**Comment by Smiley-McSmiles** [comment]
That is the prompt to the currently installed jellyfin setup, if you don't have a current jellyfin install then just press enter to skip. This feature is still experimental and will require much more code to fully support every type of install. This does not import properly from docker installs.

**Comment by dbolger** [comment]
Also having this issue - Jellyfin is already installed on my system.

**Comment by Smiley-McSmiles** [comment]
> Also having this issue - Jellyfin is already installed on my system. Not installed via Docker but through the `jellyfin-bin` package (now defunct, I think the new one is `jellyfin-server`) on Arch Linux

This script does not account for current installs of Jellyfin, you must uninstall Jellyfin first before running this script. The import function is still buggy and can't account for every situation. I have tested the install on various arch distributions and it does work.
