### ISSUE TITLE
The script is not working for latest build version jellyfin 10.8.13

### ISSUE THREAD

**Issue by hobby-lc** [Smiley-McSmiles/jellyman#54]
The filename of the latest build version is "jellyfin_10.8.13_amd64.tar.gz". The regex used in setup.sh line 258 is not able to process '.13' in the file name. FYI.

`                jellyfin_archive=$(echo "$jellyfinIndex" | grep -o jellyfin_[0-9][0-9].[0-9].[0-9].$architecture.tar.gz | head -1)`

https://github.com/Smiley-McSmiles/jellyman/blob/14711dbc07f0be3b867532ffc9e35d81dd50913b/setup.sh#L258C85-L258C85`

**Comment by Smiley-McSmiles** [comment]
I'll look into submitting a patch tomorrow. Thank you for the digging here.

**Comment by Smiley-McSmiles** [comment]
I submitted the newest release v1.6.9 to fix this issue. Thank you again for bringing this to my attention.
